name: 'Assess with PyBryt'
description: 'Run automated assessment of a repository with PyBryt'
inputs:
  submission-path:
    description: 'The path to the submission'
    required: true
  reference-urls:
    description: 'URL of a reference implementation'
    required: true
  additional-files:
    description: 'Paths to additional files to trace'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --ref-urls
    - "${{ inputs.reference-urls }}"
    - --subm
    - "${{ inputs.submission-path }}"
    - --additional-files
    - "${{ inputs.additional-files }}"
